version: '3.8'

services:
  # 1. PostgreSQL (For Auth Service)
  postgres-db:
    image: postgres:15-alpine
    container_name: ucln-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ucln-network

  # 2. MongoDB (For Catalog Service)
  mongo-db:
    image: mongo:6.0
    container_name: ucln-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: catalog_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ucln-network

  # 3. Redis (For Caching & JWT Sessions)
  redis-cache:
    image: redis:7-alpine
    container_name: ucln-redis
    ports:
      - "6379:6379"
    networks:
      - ucln-network

volumes:
  postgres_data:
  mongo_data:

networks:
  ucln-network:
    driver: bridge