version: "3.8"

services:
  auth-service:
    image: kachiliquingal/uce-auth-service:${IMAGE_TAG}
    restart: always
    command: sh -c "sleep 15 && node dist/index.js"
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
      - KAFKA_BROKERS=${KAFKA_BROKERS:-kafka:29092}
    networks:
      - microservices-network

  catalog-service:
    image: kachiliquingal/uce-catalog-service:${IMAGE_TAG}
    restart: always
    command: sh -c "sleep 15 && node dist/index.js"
    ports:
      - "3002:3002"
      - "50052:50052"
    environment:
      - PORT=3002
      - MONGO_URI=${MONGO_URI}
      - KAFKA_BROKERS=${KAFKA_BROKERS:-kafka:29092}
    networks:
      - microservices-network

  user-service:
    image: kachiliquingal/uce-user-service:${IMAGE_TAG}
    restart: always
    command: sh -c "sleep 15 && node dist/index.js"
    ports:
      - "3003:3003"
      - "50051:50051"
    environment:
      - PORT=3003
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - KAFKA_BROKERS=${KAFKA_BROKERS:-kafka:29092}
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true
