version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    networks:
      - microservices-network

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - microservices-network

  catalog-mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - /data/mongo:/data/db
    networks:
      - microservices-network

  neo4j:
    image: neo4j:5.18.1
    restart: always
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_server_memory_heap_initial__size: 256m
      NEO4J_server_memory_heap_max__size: 256m
      NEO4J_server_memory_pagecache_size: 128m
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - /data/neo4j/data:/data
      - /data/neo4j/plugins:/plugins
    networks:
      - microservices-network

  loan-mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: loan_db
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql:/var/lib/mysql
    networks:
      - microservices-network

  elasticsearch:
    image: elasticsearch:8.13.0
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - "9200:9200"
    volumes:
      - /data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - microservices-network

  couchdb:
    image: couchdb:3.3
    restart: always
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5984:5984"
    volumes:
      - /data/couchdb:/opt/couchdb/data
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true
