name: SonarQube Analysis

on:
  push:
    branches:
      - qa
      - main
  pull_request:
    branches:
      - qa
      - main

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage (Turborepo)
        run: npm run test -- --coverage
        continue-on-error: true  # Evita que el pipeline se caiga si un microservicio no tiene tests

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          # Lee los secretos configurados en GitHub Actions
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
